### ISSUE TITLE
用你编译好的报错了 

### ISSUE THREAD

**Issue by chenyongtu** [LFMJUN/douyin_rtmp#4]
C:\Users\Xab\Desktop\tool\tream>main.exe
Traceback (most recent call last):
  File "main.py", line 114, in <module>
  File "main.py", line 101, in main
TypeError: cannot unpack non-iterable NoneType object
[PYI-5688:ERROR] Failed to execute script 'main' due to unhandled exception!
[PYI-6256:WARNING] Failed to remove temporary directory: C:\Users\Xab\AppData\Lo
cal\Temp\_MEI62562

**Comment by LFMJUN** [comment]
看一下你的json

**Comment by RookieJay** [comment]
{
  "tshark_path": "E:\\Program Files\\Wireshark\\Wireshark.exe",
  "display_filter": "((rtmpt) && (_ws.col.info contains \"connect\")) || (_ws.col.info contains \"releaseStream\")",
  "interface": "以太网",
  "obs_path": "",
  "obs_config_path": ""
}
同样的问题
